SET (CMAKE_CROSSCOMPILING   TRUE)
SET (CMAKE_SYSTEM_NAME      "Linux")
SET (CMAKE_SYSTEM_PROCESSOR "riscv64")

SET(CMAKE_FIND_ROOT_PATH  /usr/riscv64-linux-gnu /usr/include/riscv64-linux-gnu /usr/lib/riscv64-linux-gnu /lib/riscv64-linux-gnu)

find_program(CMAKE_C_COMPILER NAMES riscv64-linux-gnu-gcc)
find_program(CMAKE_CXX_COMPILER NAMES riscv64-linux-gnu-g++)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(HAVE_VSNPRINTF_ERRORS_EXITCODE 0)
SET(FOLLY_HAVE_UNALIGNED_ACCESS_EXITCODE 0)
SET(FOLLY_HAVE_WEAK_SYMBOLS_EXITCODE 0)
SET(FOLLY_HAVE_LINUX_VDSO_EXITCODE 0)
SET(FOLLY_HAVE_WCHAR_SUPPORT_EXITCODE 0)

SET(FLEX_INCLUDE_DIR ${CMAKE_SYSROOT}/usr/include)
